syntax = "proto3";

package gommerce.state.v1beta;

import "validate/validate.proto";

option csharp_namespace = "Gommerce.Proto.State.V1Beta";
option go_package = "github.com/choral-io/gommerce-protobuf-go/state/v1beta;state_v1beta";
option java_package = "io.choral.gommerce.proto.state.v1beta";

service StateStoreService {
  rpc GetState(GetStateRequest) returns (GetStateResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  rpc SetState(SetStateRequest) returns (SetStateResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  rpc DelState(DelStateRequest) returns (DelStateResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetStateRequest {
  string key = 1 [(validate.rules).string.min_len = 1];
  map<string, string> metadata = 2;
}

message GetStateResponse {
  bytes data = 1;
  reserved 2;
  map<string, string> metadata = 3;
  string content_type = 4;
}

message SetStateRequest {
  string key = 1 [(validate.rules).string.min_len = 1];
  bytes data = 2;
  reserved 3;
  map<string, string> metadata = 4;
  reserved 5;
  string content_type = 6;
}

message SetStateResponse {}

message DelStateRequest {
  string key = 1 [(validate.rules).string.min_len = 1];
  reserved 2;
  map<string, string> metadata = 3;
  reserved 4;
}

message DelStateResponse {}
